import { describe, expect, it } from "vitest";
import { AssignmentWatcher } from "../src/watcher/assignment-watcher.js";
import type { AssignmentSource, ObservedAssignment, Snapshot, WatcherStore } from "../src/watcher/types.js";

class Store implements WatcherStore { snapshots = new Map<string, Snapshot>(); jobs: Array<{ key: string; priority: number }> = []; key(a: ObservedAssignment) { return `${a.courseId}:${a.courseworkId}`; } async getSnapshot(_u: string, a: ObservedAssignment) { return this.snapshots.get(this.key(a)); } async saveSnapshot(_u: string, a: ObservedAssignment, s: Snapshot) { this.snapshots.set(this.key(a), s); } async enqueue(_u: string, _a: ObservedAssignment, key: string, priority: number) { if (!this.jobs.some((job) => job.key === key)) this.jobs.push({ key, priority }); } }
describe("assignment watcher", () => {
  it("creates one job for a new assignment and none for an unchanged poll", async () => { const assignment = { courseId: "c", courseworkId: "a", title: "Lab", state: "PUBLISHED", updatedAt: "2026-09-22T00:00:00Z" }; const source: AssignmentSource = { listAssignments: async () => [assignment] }; const store = new Store(); const watcher = new AssignmentWatcher(source, store); expect(await watcher.scan("u")).toMatchObject({ created: 1 }); expect(await watcher.scan("u")).toMatchObject({ created: 0, updated: 0 }); expect(store.jobs).toHaveLength(1); });
  it("creates a replacement job after a meaningful update and prioritizes imminent due work", async () => { const assignment = { courseId: "c", courseworkId: "a", title: "Lab", state: "PUBLISHED", updatedAt: "one", dueAt: new Date(Date.now() + 3_600_000).toISOString() }; let phase = 0; const source: AssignmentSource = { listAssignments: async () => [{ ...assignment, updatedAt: phase++ ? "two" : "one" }] }; const store = new Store(); const watcher = new AssignmentWatcher(source, store); await watcher.scan("u"); expect(await watcher.scan("u")).toMatchObject({ updated: 1 }); expect(store.jobs).toHaveLength(2); expect(store.jobs[0]?.priority).toBe(100); });
});
