import { Pool } from "pg";
import { config } from "./config.js";
import type { Coursework, LearningArtifact, LearningJob, Repository, User } from "../shared/types.js";

type JobRow = { id: string; user_id: string; coursework_id: string | null; mode: LearningJob["mode"]; context_json: LearningJob["context"]; state: LearningJob["state"]; attempts: number; idempotency_key: string; result_json: LearningArtifact | null; error_code: string | null };
const asJob = (row: JobRow): LearningJob => ({ id: row.id, userId: row.user_id, courseworkId: row.coursework_id ?? undefined, mode: row.mode, context: row.context_json, state: row.state, attempts: row.attempts, idempotencyKey: row.idempotency_key, result: row.result_json ?? undefined, errorCode: row.error_code ?? undefined });

/** PostgreSQL adapter. Job claiming uses SKIP LOCKED so independent workers cannot process a job twice. */
export class PostgresRepository implements Repository {
  private pool: Pool;
  constructor(url = config.DATABASE_URL) { if (!url) throw new Error("DATABASE_URL is required when DEMO_MODE=false"); this.pool = new Pool({ connectionString: url, max: 10, ssl: config.NODE_ENV === "production" ? { rejectUnauthorized: true } : undefined }); }
  async upsertUser(googleSubject: string, email?: string): Promise<User> { const { rows } = await this.pool.query<User>(`INSERT INTO app_user (google_subject,email) VALUES ($1,$2) ON CONFLICT (google_subject) DO UPDATE SET email=EXCLUDED.email RETURNING id, google_subject AS "googleSubject", email`, [googleSubject, email ?? null]); return rows[0]!; }
  async getUser(id: string): Promise<User | undefined> { const { rows } = await this.pool.query<User>(`SELECT id,google_subject AS "googleSubject",email FROM app_user WHERE id=$1 AND deletion_requested_at IS NULL`, [id]); return rows[0]; }
  async listCoursework(userId: string): Promise<Coursework[]> { const { rows } = await this.pool.query<Coursework>(`SELECT id,user_id AS "userId",provider_course_id AS "courseId",provider_coursework_id AS "courseworkId",title,due_at AS "dueAt",state,source_updated_at AS "updatedAt" FROM coursework WHERE user_id=$1 ORDER BY due_at NULLS LAST,title`, [userId]); return rows; }
  async createJob(job: Omit<LearningJob, "id" | "state" | "attempts">): Promise<LearningJob> { const { rows } = await this.pool.query<JobRow>(`INSERT INTO learning_job (user_id,coursework_id,mode,context_json,idempotency_key) VALUES ($1,$2,$3,$4,$5) ON CONFLICT (user_id,idempotency_key) DO UPDATE SET id=learning_job.id RETURNING *`, [job.userId, job.courseworkId ?? null, job.mode, job.context, job.idempotencyKey]); return asJob(rows[0]!); }
  async getJob(userId: string, id: string): Promise<LearningJob | undefined> { const { rows } = await this.pool.query<JobRow>(`SELECT * FROM learning_job WHERE id=$1 AND user_id=$2`, [id,userId]); return rows[0] ? asJob(rows[0]) : undefined; }
  async claimJob(): Promise<LearningJob | undefined> { const client = await this.pool.connect(); try { await client.query("BEGIN"); const { rows } = await client.query<JobRow>(`WITH candidate AS (SELECT id FROM learning_job WHERE state='queued' ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 1) UPDATE learning_job j SET state='running',attempts=attempts+1,updated_at=now() FROM candidate WHERE j.id=candidate.id RETURNING j.*`); await client.query("COMMIT"); return rows[0] ? asJob(rows[0]) : undefined; } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); } }
  async finishJob(id: string, result: LearningArtifact) { await this.pool.query(`UPDATE learning_job SET state='succeeded',result_json=$2,updated_at=now() WHERE id=$1 AND state='running'`, [id,result]); }
  async failJob(id: string, code: string) { await this.pool.query(`UPDATE learning_job SET state='failed',error_code=$2,updated_at=now() WHERE id=$1 AND state='running'`, [id,code]); }
  async audit(userId: string | undefined, action: string, target: string | undefined, outcome: string, correlationId: string) { await this.pool.query(`INSERT INTO audit_event (user_id,action,target_ref,outcome,correlation_id) VALUES ($1,$2,$3,$4,$5)`, [userId ?? null,action,target ?? null,outcome,correlationId]); }
  async revokeConnection(userId: string) { await this.pool.query(`UPDATE oauth_connection SET revoked_at=now(),encrypted_refresh_token='' WHERE user_id=$1 AND provider='google'`, [userId]); }
  async storeGoogleConnection(userId: string, encryptedRefreshToken: string, scopes: string[], expiresAt?: string) { await this.pool.query(`INSERT INTO oauth_connection (user_id,provider,scopes,encrypted_refresh_token,expires_at) VALUES ($1,'google',$2,$3,$4) ON CONFLICT (user_id,provider) DO UPDATE SET scopes=EXCLUDED.scopes,encrypted_refresh_token=EXCLUDED.encrypted_refresh_token,expires_at=EXCLUDED.expires_at,revoked_at=NULL`, [userId,scopes,encryptedRefreshToken,expiresAt ?? null]); }
  async requestDeletion(userId: string) { const client = await this.pool.connect(); try { await client.query("BEGIN"); await client.query(`UPDATE oauth_connection SET revoked_at=now(),encrypted_refresh_token='' WHERE user_id=$1`, [userId]); await client.query(`UPDATE app_user SET deletion_requested_at=now() WHERE id=$1`, [userId]); await client.query("COMMIT"); } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); } }
  async upsertCoursework(items: Coursework[]) { if (!items.length) return; const client = await this.pool.connect(); try { await client.query("BEGIN"); for (const item of items) await client.query(`INSERT INTO coursework (user_id,provider_course_id,provider_coursework_id,title,due_at,state,source_updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7) ON CONFLICT (user_id,provider_course_id,provider_coursework_id) DO UPDATE SET title=EXCLUDED.title,due_at=EXCLUDED.due_at,state=EXCLUDED.state,source_updated_at=EXCLUDED.source_updated_at`, [item.userId,item.courseId,item.courseworkId,item.title,item.dueAt ?? null,item.state,item.updatedAt]); await client.query("COMMIT"); } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); } }
  async getGoogleConnection(userId: string) { const { rows } = await this.pool.query<{ encryptedRefreshToken: string }>(`SELECT encrypted_refresh_token AS "encryptedRefreshToken" FROM oauth_connection WHERE user_id=$1 AND provider='google' AND revoked_at IS NULL AND encrypted_refresh_token<>''`, [userId]); return rows[0]; }
}
